Feature/authentication
sketchfab/sculptgl pull request #1
Opened 2016-11-25 14:50 UTC by mauricesvay

2016-12-03 20:31 UTC, pierreant-p requested changes

2016-12-03 20:31 UTC, pierreant-p commented on lib/sketchfab-upload.js
> +        console.log('Error');
did you leave these on purpose?

2016-12-06 17:19 UTC, mauricesvay commented on lib/sketchfab-upload.js
> +        console.log('Error');
Fixed, it was some code I forgot to remove while experimenting.

2016-12-07 11:01 UTC, pierreant-p approved these changes

2016-12-07 11:01 UTC, merged